// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrtQ4HNKYG56qHE8TzU8VMSba8ynl0lRo',
    appId: '1:113731870223:web:41ef07095acf1ea439cd7a',
    messagingSenderId: '113731870223',
    projectId: 'be-for-real',
    authDomain: 'be-for-real.firebaseapp.com',
    storageBucket: 'be-for-real.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1_Hd69EloTSSNKkT8gRYPUSfj0K9Mzs',
    appId: '1:113731870223:android:23dbe0348058eae339cd7a',
    messagingSenderId: '113731870223',
    projectId: 'be-for-real',
    storageBucket: 'be-for-real.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNcbcVrTRO-r4ET8g_TCqWPBOvSeh8AMI',
    appId: '1:113731870223:ios:079a7e524d625b5139cd7a',
    messagingSenderId: '113731870223',
    projectId: 'be-for-real',
    storageBucket: 'be-for-real.appspot.com',
    iosClientId: '113731870223-0aftb78ai86dg0mfv9cthvcl1jdap1lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.beForReal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNcbcVrTRO-r4ET8g_TCqWPBOvSeh8AMI',
    appId: '1:113731870223:ios:079a7e524d625b5139cd7a',
    messagingSenderId: '113731870223',
    projectId: 'be-for-real',
    storageBucket: 'be-for-real.appspot.com',
    iosClientId: '113731870223-0aftb78ai86dg0mfv9cthvcl1jdap1lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.beForReal',
  );
}